{pkgs, ...}: {
  home.packages = with pkgs; [
    # --- Bash/shell ---
    bash-language-server
    shfmt # Shell formatter
    shellcheck # Shell linter

    # --- C#/.net/f# ---
    omnisharp-roslyn

    # --- C/c++ ---
    clang-tools # Includes clang-format

    # --- Cmake ---
    cmake-language-server
    cmake-format

    # --- Clojure ---
    clojure-lsp
    cljfmt # Formatter

    # --- Common Lisp ---
    sbcl # Common Lisp compiler (Steel Bank Common Lisp)

    # --- Crystal ---
    crystalline

    # --- Css/html/json ---
    vscode-langservers-extracted # NOTE: Includes html, css, json, eslint

    # --- D Language ---
    serve-d

    # # --- Dart/Flutter ---
    # dart
    # flutter

    # --- Deno ---
    # Alt Typescript Runtime
    deno

    # --- Dhall ---
    dhall-lsp-server

    # --- Docker ---
    nodePackages.dockerfile-language-server-nodejs

    # --- Elixir/erlang ---
    elixir-ls
    erlang-ls

    # --- Elm ---
    elmPackages.elm-format
    elmPackages.elm-language-server

    # --- Emmet ---
    emmet-ls

    # --- F# ---
    fsautocomplete

    # --- Fennel ---
    fennel-ls

    # --- Fish Shell ---
    fish-lsp

    # --- Fortran ---
    fortls
    fprettify # Formatter

    # --- Glsl ---
    glslls

    # --- General ---
    nodePackages.prettier
    prettierd # NOTE: Prettier running as daemon

    # --- Go ---
    goimports-reviser
    gopls
    gofumpt

    # --- Graphql (as Nodepackage) ---
    nodePackages.graphql-language-service-cli

    # --- Haskell ---
    haskell-language-server
    haskellPackages.fourmolu # or haskellPackages.ormolu

    # --- Java ---
    google-java-format
    jdt-language-server # Eclipse JDT LS

    # --- Javascript/Typescript/React.js/Next.js ---
    nodePackages.eslint
    nodePackages.npm
    nodePackages.prettier
    nodePackages.typescript-language-server
    biome

    # --- Just ---
    just-lsp

    # --- Kdl ---
    kdlfmt

    # --- Kotlin ---
    kotlin-language-server

    # --- Latex ---
    texlab
    texlivePackages.latexindent

    # --- Lua ---
    lua-language-server
    stylua

    # --- Markdown ---
    markdown-oxide
    marksman

    # --- Nix ---
    nil # Original language server
    nixd # Latest language server
    nixpkgs-fmt # Formatter
    nixfmt-rfc-style # Official formatter
    alejandra # Opinionated formatter

    # --- Ocaml ---
    ocamlPackages.ocaml-lsp
    ocamlPackages.ocamlformat

    # --- Perl ---
    perlnavigator

    # --- Php ---
    intelephense # NOTE: Alternative: phpactor

    # --- Prisma ---
    prisma-engines

    # --- Protocol Buffers ---
    buf

    # --- Python ---
    isort # Python import sorter
    pyright # Type checker
    ruff # Fast Python formatter/linter

    # --- R ---
    rPackages.styler
    rPackages.languageserver

    # --- Rust ---
    bacon # Background rust code checker
    cargo-info # Cargo subcommand to show crates info from crates.io
    rusty-man # Command-line viewer for documentation generated by rustdoc

    # --- Sql ---
    sqls # SQL language server
    sqlfluff # Formatter

    # --- Scala ---
    metals
    scalafmt # Formatter

    # --- Svelte ---
    svelte-language-server

    # --- Swift ---
    sourcekit-lsp

    # --- Toml ---
    taplo

    # --- Tailwind Css ---
    tailwindcss-language-server

    # --- Terraform ---
    terraform-ls

    # --- Typst ---
    tinymist # Integrated language server for typst (includes formatters)

    # --- Vue ---
    vue-language-server

    # --- Xml ---
    lemminx

    # --- Yaml ---
    yaml-language-server

    # --- Zig ---
    zls # Zig Language Server
  ];
}
