require("conform").setup({
	formatters_by_ft = {
		python = { "ruff_format" },
		lua = { "stylua" },
		rust = { "rustfmt", lsp_format = "fallback" },
		javascript = { "prettierd", "prettier", stop_after_first = true },
		sh = { "shfmt" },
		bash = { "shfmt" },
		c = { "clang_format" },
		cpp = { "clang_format" },
		clojure = { "cljfmt" },
		css = { "prettierd", "prettier" },
		html = { "prettierd", "prettier" },
		json = { "prettierd", "prettier" },
		jsonc = { "prettierd", "prettier" },
		elixir = { "mix_format" },
		elm = { "elm_format" },
		go = { "goimports_reviser", "gofumpt", "go_mod_tidy" },
		haskell = { "fourmolu" },
		java = { "google_java_format" },
		javascriptreact = { "prettierd", "prettier", stop_after_first = true },
		kdl = { "kdlfmt" },
		typescript = { "prettierd", "prettier", stop_after_first = true },
		typescriptreact = { "prettierd", "prettier", stop_after_first = true },
		latex = { "latexindent" },
		nix = { "nixpkgs_fmt", "alejandra" },
		ocaml = { "ocamlformat" },
		scala = { "scalafmt" },
		toml = { "taplo" },
		yaml = { "prettierd", "prettier" },
		zig = { "zigfmt" },
		fish = { "fish_indent" },
		cmake = { "cmake_format" },
		terraform = { "terraform_fmt" },
		fortran = { "fprettify" },
		crystal = { "crystal_format" },
		proto = { "buf_format" },
		dhall = { "dhall" },
		prisma = { "prisma_format" },
	},
	lsp_fallback = true,
})
