vim.o.clipboard = 'unnamedplus' -- Enable system clipboard
vim.o.showmode = false -- We already have this on line
vim.o.encoding = 'utf-8'
vim.o.fileencoding = 'utf-8'
vim.o.mouse = 'a' -- Enable mouse support
vim.g.mapleader = ' ' -- Leader
vim.g.maplocalleader = ' ' -- Local leader
vim.o.swapfile = false -- Disable swap 
vim.o.updatetime = 300
vim.o.hidden = true -- Enable background buffers
vim.o.history = 5000 -- Remember N lines in history
vim.o.lazyredraw = true -- Faster scrolling
vim.o.synmaxcol = 240 -- Max column for syntax highlight
vim.o.updatetime = 250 -- ms to wait for trigger an event
