#!/usr/bin/env bash

set -euo pipefail

# --- Main Configuration ---
APP_NAME="rhodium-colors"
APP_TITLE="Rhodium's Color Utils"
PROMPT="β: "

# --- Imports ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/shared-functions.sh" ]]; then
    source "$SCRIPT_DIR/shared-functions.sh"
else
    echo "Error: shared-functions.sh not found" >&2
    exit 1
fi

# Location of the Unicode symbol list in this script (adjust if you externalize it)
UNICODE_SYMBOL_LIST=$(cat <<'EOF'
+	Plus	(Mathematical, Operators)
−	Minus	(Mathematical, Operators)
×	Multiply	(Mathematical, Operators)
÷	Divide	(Mathematical, Operators)
=	Equal	(Mathematical, Operators)
≠	Not Equal	(Mathematical, Operators)
≈	Approx	(Mathematical, Operators)
±	Plus Minus	(Mathematical, Operators)
∓	Minus Plus	(Mathematical, Operators)
∝	Proportional	(Mathematical, Operators)
°	Degree	(Mathematical, Operators)
<	Less Than	(Mathematical, Comparison)
>	Greater Than	(Mathematical, Comparison)
≤	Less Than Equal	(Mathematical, Comparison)
≥	Greater Than Equal	(Mathematical, Comparison)
≪	Much Less Than	(Mathematical, Comparison)
≫	Much Greater Than	(Mathematical, Comparison)
∈	Element Of	(Mathematical, Sets)
∉	Not Element Of	(Mathematical, Sets)
⊂	Subset	(Mathematical, Sets)
⊃	Superset	(Mathematical, Sets)
⊆	Subset Equal	(Mathematical, Sets)
⊇	Superset Equal	(Mathematical, Sets)
∩	Intersection	(Mathematical, Sets)
∪	Union	(Mathematical, Sets)
∅	Empty Set	(Mathematical, Sets)
∀	For All	(Mathematical, Logic)
∃	There Exists	(Mathematical, Logic)
∄	There Not Exists	(Mathematical, Logic)
∧	Logical And	(Mathematical, Logic)
∨	Logical Or	(Mathematical, Logic)
⊥	Up Tack	(Mathematical, Logic)
⊤	Down Tack	(Mathematical, Logic)
⊢	Right Tack	(Mathematical, Logic)
⊣	Left Tack	(Mathematical, Logic)
∞	Infinity	(Mathematical, Calculus)
∂	Partial	(Mathematical, Calculus)
∇	Gradient	(Mathematical, Calculus)
∆	Increment	(Mathematical, Calculus)
∑	Sum	(Mathematical, Calculus)
∏	Product	(Mathematical, Calculus)
∫	Integral	(Mathematical, Calculus)
∬	Double Integral	(Mathematical, Calculus)
∭	Triple Integral	(Mathematical, Calculus)
∮	Contour Integral	(Mathematical, Calculus)
√	Square Root	(Mathematical, Roots)
∛	Cube Root	(Mathematical, Roots)
∜	Fourth Root	(Mathematical, Roots)
∠	Angle	(Mathematical, Misc)
∣	Divides	(Mathematical, Misc)
∥	Parallel	(Mathematical, Misc)
′	Prime	(Mathematical, Misc)
″	Double Prime	(Mathematical, Misc)
‴	Triple Prime	(Mathematical, Misc)
λ	Lambda	(Mathematical, Misc)
⊹	Hermitian Matrix	(Mathematical, Misc)
⊶	Original Of	(Mathematical, Misc)
⊷	Image Of	(Mathematical, Misc)
⊸	Multimap	(Mathematical, Misc)
⊺	Intercalate	(Mathematical, Misc)
⊻	XOR	(Mathematical, Misc)
⊼	NAND	(Mathematical, Misc)
⊽	NOR	(Mathematical, Misc)
$	Dollar	(Currency)
¢	Cent	(Currency)
£	Pound	(Currency)
¤	Currency	(Currency)
¥	Yen	(Currency)
¦	Broken Bar	(Currency)
§	Section	(Currency)
¨	Diaeresis	(Currency)
©	Copyright	(Currency)
ª	Ordinal Feminine	(Currency)
¬	Not Sign	(Currency)
®	Registered	(Currency)
¯	Macron	(Currency)
•	Bullet	(Typography, Punctuation)
‣	Triangle Bullet	(Typography, Punctuation)
·	Interpunct	(Typography, Punctuation)
…	Ellipsis	(Typography, Punctuation)
⁃	Hyphen Bullet	(Typography, Punctuation)
«	Left Angle Quote	(Typography, Quotes)
»	Right Angle Quote	(Typography, Quotes)
-	Hyphen	(Typography, Dashes)
–	Ndash	(Typography, Dashes)
—	Mdash	(Typography, Dashes)
―	Horizontal Bar	(Typography, Dashes)
¶	Paragraph	(Typography, Marks)
†	Dagger	(Typography, Marks)
‡	Double Dagger	(Typography, Marks)
‰	Permille	(Typography, Marks)
※	Reference	(Typography, Marks)
░	Light	(Loading, Shades)
▒	Medium	(Loading, Shades)
▓	Dark	(Loading, Shades)
█	Full	(Loading, Shades)
▀	Upper Half	(Loading, Blocks)
▄	Lower Half	(Loading, Blocks)
▉	Left Seven Eighths	(Loading, Blocks)
▊	Left Three Quarters	(Loading, Blocks)
▋	Left Five Eighths	(Loading, Blocks)
▌	Left Half	(Loading, Blocks)
▍	Left Three Eighths	(Loading, Blocks)
▎	Left Quarter	(Loading, Blocks)
▏	Left Eighth	(Loading, Blocks)
▐	Right Half	(Loading, Blocks)
▘	Upper Left	(Loading, Quadrants)
▝	Upper Right	(Loading, Quadrants)
▖	Lower Left	(Loading, Quadrants)
▗	Lower Right	(Loading, Quadrants)
▚	Upper Left Lower Right	(Loading, Quadrants)
▞	Upper Right Lower Left	(Loading, Quadrants)
─	Horizontal	(Box Drawing, Single)
│	Vertical	(Box Drawing, Single)
┌	Down Right	(Box Drawing, Single)
┐	Down Left	(Box Drawing, Single)
└	Up Right	(Box Drawing, Single)
┘	Up Left	(Box Drawing, Single)
├	Vertical Right	(Box Drawing, Single)
┤	Vertical Left	(Box Drawing, Single)
┬	Down Horizontal	(Box Drawing, Single)
┴	Up Horizontal	(Box Drawing, Single)
┼	Cross	(Box Drawing, Single)
═	Horizontal	(Box Drawing, Double)
║	Vertical	(Box Drawing, Double)
╔	Down Right	(Box Drawing, Double)
╗	Down Left	(Box Drawing, Double)
╚	Up Right	(Box Drawing, Double)
╝	Up Left	(Box Drawing, Double)
╠	Vertical Right	(Box Drawing, Double)
╣	Vertical Left	(Box Drawing, Double)
╦	Down Horizontal	(Box Drawing, Double)
╩	Up Horizontal	(Box Drawing, Double)
╬	Cross	(Box Drawing, Double)
╒	Down Single Right Double	(Box Drawing, Mixed)
╓	Down Double Right Single	(Box Drawing, Mixed)
╕	Down Single Left Double	(Box Drawing, Mixed)
╖	Down Double Left Single	(Box Drawing, Mixed)
╘	Up Single Right Double	(Box Drawing, Mixed)
╙	Up Double Right Single	(Box Drawing, Mixed)
╛	Up Single Left Double	(Box Drawing, Mixed)
╜	Up Double Left Single	(Box Drawing, Mixed)
╞	Vertical Single Right Double	(Box Drawing, Mixed)
╟	Vertical Double Right Single	(Box Drawing, Mixed)
╡	Vertical Single Left Double	(Box Drawing, Mixed)
╢	Vertical Double Left Single	(Box Drawing, Mixed)
╤	Down Single Horizontal Double	(Box Drawing, Mixed)
╥	Down Double Horizontal Single	(Box Drawing, Mixed)
╧	Up Single Horizontal Double	(Box Drawing, Mixed)
╨	Up Double Horizontal Single	(Box Drawing, Mixed)
╪	Vertical Single Horizontal Double	(Box Drawing, Mixed)
╫	Vertical Double Horizontal Single	(Box Drawing, Mixed)
╭	Down Right	(Box Drawing, Rounded)
╮	Down Left	(Box Drawing, Rounded)
╯	Up Left	(Box Drawing, Rounded)
╰	Up Right	(Box Drawing, Rounded)
━	Horizontal	(Box Drawing, Heavy)
┃	Vertical	(Box Drawing, Heavy)
┏	Down Right	(Box Drawing, Heavy)
┓	Down Left	(Box Drawing, Heavy)
┗	Up Right	(Box Drawing, Heavy)
┛	Up Left	(Box Drawing, Heavy)
┣	Vertical Right	(Box Drawing, Heavy)
┫	Vertical Left	(Box Drawing, Heavy)
┳	Down Horizontal	(Box Drawing, Heavy)
┻	Up Horizontal	(Box Drawing, Heavy)
╋	Cross	(Box Drawing, Heavy)
╌	Horizontal Double	(Box Drawing, Dashed)
┄	Horizontal Triple	(Box Drawing, Dashed)
┈	Horizontal Quadruple	(Box Drawing, Dashed)
╎	Vertical Double	(Box Drawing, Dashed)
┆	Vertical Triple	(Box Drawing, Dashed)
┊	Vertical Quadruple	(Box Drawing, Dashed)
←	Left	(Arrows, Basic)
↑	Up	(Arrows, Basic)
→	Right	(Arrows, Basic)
↓	Down	(Arrows, Basic)
↔	Left Right	(Arrows, Basic)
↕	Up Down	(Arrows, Basic)
↖	North West	(Arrows, Basic)
↗	North East	(Arrows, Basic)
↘	South East	(Arrows, Basic)
↙	South West	(Arrows, Basic)
⇐	Left	(Arrows, Double)
⇑	Up	(Arrows, Double)
⇒	Right	(Arrows, Double)
⇓	Down	(Arrows, Double)
⇔	Left Right	(Arrows, Double)
⇕	Up Down	(Arrows, Double)
↤	Left From Bar	(Arrows, Barred)
↥	Up From Bar	(Arrows, Barred)
↦	Right From Bar	(Arrows, Barred)
↧	Down From Bar	(Arrows, Barred)
↨	Up Down Bar	(Arrows, Barred)
↩	Left Hook	(Arrows, Barred)
↪	Right Hook	(Arrows, Barred)
↞	Left	(Arrows, Two Headed)
↟	Up	(Arrows, Two Headed)
↠	Right	(Arrows, Two Headed)
↡	Down	(Arrows, Two Headed)
↼	Left Up	(Arrows, Harpoons)
↽	Left Down	(Arrows, Harpoons)
⇀	Right Up	(Arrows, Harpoons)
⇁	Right Down	(Arrows, Harpoons)
↾	Up Right	(Arrows, Harpoons)
↿	Up Left	(Arrows, Harpoons)
⇂	Down Right	(Arrows, Harpoons)
⇃	Down Left	(Arrows, Harpoons)
◄	Left	(Arrows, Triangular)
▲	Up	(Arrows, Triangular)
►	Right	(Arrows, Triangular)
▼	Down	(Arrows, Triangular)
◂	Left Small	(Arrows, Triangular)
▴	Up Small	(Arrows, Triangular)
▸	Right Small	(Arrows, Triangular)
▾	Down Small	(Arrows, Triangular)
□	White Square	(Geometric, Shapes)
■	Black Square	(Geometric, Shapes)
▢	Rounded Square	(Geometric, Shapes)
△	White Triangle Up	(Geometric, Shapes)
▲	Black Triangle Up	(Geometric, Shapes)
▷	White Triangle Right	(Geometric, Shapes)
▶	Black Triangle Right	(Geometric, Shapes)
▽	White Triangle Down	(Geometric, Shapes)
▼	Black Triangle Down	(Geometric, Shapes)
◁	White Triangle Left	(Geometric, Shapes)
◀	Black Triangle Left	(Geometric, Shapes)
◇	White Diamond	(Geometric, Shapes)
◆	Black Diamond	(Geometric, Shapes)
○	White Circle	(Geometric, Shapes)
●	Black Circle	(Geometric, Shapes)
◌	Dotted Circle	(Geometric, Shapes)
◐	Left Half Circle	(Geometric, Misc)
◑	Right Half Circle	(Geometric, Misc)
◓	Upper Half Circle	(Geometric, Misc)
◒	Lower Half Circle	(Geometric, Misc)
◍	Circle With Vertical Fill	(Geometric, Misc)
◙	Inverse White Circle	(Geometric, Misc)
◴	Upper Left Quadrant	(Geometric, Misc)
◵	Upper Right Quadrant	(Geometric, Misc)
◶	Lower Left Quadrant	(Geometric, Misc)
◷	Lower Right Quadrant	(Geometric, Misc)
⌀	Diameter	(Technical, Engineering)
⌬	Benzene Ring	(Technical, Engineering)
⌃	Up Arrowhead	(Technical, Engineering)
⌄	Down Arrowhead	(Technical, Engineering)
⌅	Projective	(Technical, Engineering)
⌆	Perspective	(Technical, Engineering)
⌈	Left Ceiling	(Technical, Brackets)
⌉	Right Ceiling	(Technical, Brackets)
⌊	Left Floor	(Technical, Brackets)
⌋	Right Floor	(Technical, Brackets)
⌍	Bottom Left Crop	(Technical, Brackets)
⌎	Bottom Right Crop	(Technical, Brackets)
⌏	Top Left Crop	(Technical, Brackets)
⌐	Top Right Crop	(Technical, Brackets)
⎕	Quad	(Technical, APL)
⍞	Quad Quote	(Technical, APL)
⌽	Circle Stile	(Technical, APL)
∘	Jot	(Technical, APL)
⍝	Lamp	(Technical, APL)
⍋	Delta Stile	(Technical, APL)
⍒	Del Stile	(Technical, APL)
⌺	Quad Diamond	(Technical, APL)
α	Alpha	(Technical, Greek, Lowercase)
β	Beta	(Technical, Greek, Lowercase)
γ	Gamma	(Technical, Greek, Lowercase)
δ	Delta	(Technical, Greek, Lowercase)
ε	Epsilon	(Technical, Greek, Lowercase)
ζ	Zeta	(Technical, Greek, Lowercase)
η	Eta	(Technical, Greek, Lowercase)
θ	Theta	(Technical, Greek, Lowercase)
ι	Iota	(Technical, Greek, Lowercase)
κ	Kappa	(Technical, Greek, Lowercase)
λ	Lambda	(Technical, Greek, Lowercase)
μ	Mu	(Technical, Greek, Lowercase)
ν	Nu	(Technical, Greek, Lowercase)
ξ	Xi	(Technical, Greek, Lowercase)
ο	Omicron	(Technical, Greek, Lowercase)
π	Pi	(Technical, Greek, Lowercase)
ρ	Rho	(Technical, Greek, Lowercase)
σ	Sigma	(Technical, Greek, Lowercase)
τ	Tau	(Technical, Greek, Lowercase)
υ	Upsilon	(Technical, Greek, Lowercase)
φ	Phi	(Technical, Greek, Lowercase)
χ	Chi	(Technical, Greek, Lowercase)
ψ	Psi	(Technical, Greek, Lowercase)
ω	Omega	(Technical, Greek, Lowercase)
Α	Alpha	(Technical, Greek, Uppercase)
Β	Beta	(Technical, Greek, Uppercase)
Γ	Gamma	(Technical, Greek, Uppercase)
Δ	Delta	(Technical, Greek, Uppercase)
Ε	Epsilon	(Technical, Greek, Uppercase)
Ζ	Zeta	(Technical, Greek, Uppercase)
Η	Eta	(Technical, Greek, Uppercase)
Θ	Theta	(Technical, Greek, Uppercase)
Ι	Iota	(Technical, Greek, Uppercase)
Κ	Kappa	(Technical, Greek, Uppercase)
Λ	Lambda	(Technical, Greek, Uppercase)
Μ	Mu	(Technical, Greek, Uppercase)
Ν	Nu	(Technical, Greek, Uppercase)
Ξ	Xi	(Technical, Greek, Uppercase)
Ο	Omicron	(Technical, Greek, Uppercase)
Π	Pi	(Technical, Greek, Uppercase)
Ρ	Rho	(Technical, Greek, Uppercase)
Σ	Sigma	(Technical, Greek, Uppercase)
Τ	Tau	(Technical, Greek, Uppercase)
Υ	Upsilon	(Technical, Greek, Uppercase)
Φ	Phi	(Technical, Greek, Uppercase)
Χ	Chi	(Technical, Greek, Uppercase)
Ψ	Psi	(Technical, Greek, Uppercase)
Ω	Omega	(Technical, Greek, Uppercase)
✓	Check	(Technical, Status, Marks)
✗	Cross	(Technical, Status, Marks)
!	Exclamation	(Technical, Status, Punctuation)
?	Question	(Technical, Status, Punctuation)
‼	Double Exclamation	(Technical, Status, Punctuation)
⁉	Exclamation Question	(Technical, Status, Punctuation)
ℹ	Information	(Technical, Status, Punctuation)
⠀	Blank	(Technical, Braille, Patterns 1)
⠁	Dot 1	(Technical, Braille, Patterns 1)
⠂	Dot 2	(Technical, Braille, Patterns 1)
⠃	Dot 12	(Technical, Braille, Patterns 1)
⠄	Dot 3	(Technical, Braille, Patterns 1)
⠅	Dot 13	(Technical, Braille, Patterns 1)
⠆	Dot 23	(Technical, Braille, Patterns 1)
⠇	Dot 123	(Technical, Braille, Patterns 1)
⠈	Dot 4	(Technical, Braille, Patterns 1)
⠉	Dot 14	(Technical, Braille, Patterns 1)
⠊	Dot 24	(Technical, Braille, Patterns 1)
⠋	Dot 124	(Technical, Braille, Patterns 1)
⠌	Dot 34	(Technical, Braille, Patterns 1)
⠍	Dot 134	(Technical, Braille, Patterns 1)
⠎	Dot 234	(Technical, Braille, Patterns 1)
⠏	Dot 1234	(Technical, Braille, Patterns 1)
⠐	Dot 5	(Technical, Braille, Patterns 2)
⠑	Dot 15	(Technical, Braille, Patterns 2)
⠒	Dot 25	(Technical, Braille, Patterns 2)
⠓	Dot 125	(Technical, Braille, Patterns 2)
⠔	Dot 35	(Technical, Braille, Patterns 2)
⠕	Dot 135	(Technical, Braille, Patterns 2)
⠖	Dot 235	(Technical, Braille, Patterns 2)
⠗	Dot 1235	(Technical, Braille, Patterns 2)
⠘	Dot 45	(Technical, Braille, Patterns 2)
⠙	Dot 145	(Technical, Braille, Patterns 2)
⠚	Dot 245	(Technical, Braille, Patterns 2)
⠛	Dot 1245	(Technical, Braille, Patterns 2)
⠜	Dot 345	(Technical, Braille, Patterns 2)
⠝	Dot 1345	(Technical, Braille, Patterns 2)
⠞	Dot 2345	(Technical, Braille, Patterns 2)
⠟	Dot 12345	(Technical, Braille, Patterns 2)
⠠	Dot 6	(Technical, Braille, Patterns 3)
⠡	Dot 16	(Technical, Braille, Patterns 3)
⠢	Dot 26	(Technical, Braille, Patterns 3)
⠣	Dot 126	(Technical, Braille, Patterns 3)
⠤	Dot 36	(Technical, Braille, Patterns 3)
⠥	Dot 136	(Technical, Braille, Patterns 3)
⠦	Dot 236	(Technical, Braille, Patterns 3)
⠧	Dot 1236	(Technical, Braille, Patterns 3)
⠨	Dot 46	(Technical, Braille, Patterns 3)
⠩	Dot 146	(Technical, Braille, Patterns 3)
⠪	Dot 246	(Technical, Braille, Patterns 3)
⠫	Dot 1246	(Technical, Braille, Patterns 3)
⠬	Dot 346	(Technical, Braille, Patterns 3)
⠭	Dot 1346	(Technical, Braille, Patterns 3)
⠮	Dot 2346	(Technical, Braille, Patterns 3)
⠯	Dot 12346	(Technical, Braille, Patterns 3)
⠰	Dot 56	(Technical, Braille, Patterns 4)
⠱	Dot 156	(Technical, Braille, Patterns 4)
⠲	Dot 256	(Technical, Braille, Patterns 4)
⠳	Dot 1256	(Technical, Braille, Patterns 4)
⠴	Dot 356	(Technical, Braille, Patterns 4)
⠵	Dot 1356	(Technical, Braille, Patterns 4)
⠶	Dot 2356	(Technical, Braille, Patterns 4)
⠷	Dot 12356	(Technical, Braille, Patterns 4)
⠸	Dot 456	(Technical, Braille, Patterns 4)
⠹	Dot 1456	(Technical, Braille, Patterns 4)
⠺	Dot 2456	(Technical, Braille, Patterns 4)
⠻	Dot 12456	(Technical, Braille, Patterns 4)
⠼	Dot 3456	(Technical, Braille, Patterns 4)
⠽	Dot 13456	(Technical, Braille, Patterns 4)
⠾	Dot 23456	(Technical, Braille, Patterns 4)
⠿	Dot 123456	(Technical, Braille, Patterns 4)
EOF
)

# Extract unique categories
get_categories() {
    echo "$UNICODE_SYMBOL_LIST" |
        grep -oP '\(\K[^)]+' |
        tr ',' '\n' |
        sed 's/^ *//;s/ *$//' |
        sort -u
}

# Show fuzzel menu for category selection
select_category() {
    get_categories | fuzzel --dmenu --prompt "Category: "
}

# Filter symbols by selected category
filter_symbols_by_category() {
    local category="$1"
    echo "$UNICODE_SYMBOL_LIST" | grep "$category"
}

# Let user select a symbol from filtered list
select_symbol() {
    local filtered="$1"
    echo "$filtered" | fuzzel --dmenu --prompt "Symbol: "
}

# Extract the symbol (1st field) from the selected line
extract_symbol() {
    echo "$1" | awk -F'\t' '{print $1}'
}

# Main logic
main() {
    selected_category=$(select_category) || exit 1
    matching_symbols=$(filter_symbols_by_category "$selected_category")
    selected_line=$(select_symbol "$matching_symbols") || exit 1
    selected_symbol=$(extract_symbol "$selected_line")
    echo -n "$selected_symbol" | wl-copy
    notify-send "Symbol Picker" "Symbol copied to clipboard: $selected_symbol"
}

main
